spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiamu?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8074

dubbo:
  application:
    name: dubbo-demo-client
    logger: slf4j
  protocol: # 设置dubbo传输协议
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181