server:
  port: 8075

dubbo:
  application:
    name: dubbo-demo-server
    logger: slf4j
  protocol: # 设置dubbo传输协议
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
